PY = python3
NUM = 05
DIR = /staff/masato/t/$(NUM)/

default-target:
	@echo "Usage:"
	@echo "make up1 or make up2 or ... "


up0:
	$(PY) $(DIR)test00.py 00.txt

up1:
	$(PY) $(DIR)test01.py 01.c

up2:
	$(PY) $(DIR)test02.py 02.c

up3:
	$(PY) $(DIR)test03.py 03.c

up4:
	$(PY) $(DIR)test04.py 04.c

up5:
	$(PY) $(DIR)test05.py 05.txt

