PY = python3
NUM = 15
DIR = /staff/masato/t/$(NUM)/

default-target:
	@echo "Usage:"
	@echo "make up1 or make up2 or ... "

up1:
	$(PY) $(DIR)test01.py 01.c

up2:
	$(PY) $(DIR)test02.py 02.c

up3:
	$(PY) $(DIR)test03.py 03.c
	
